name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: [2.0.16, 2.2.4]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nim
        uses: iffy/install-nim@v4
        with:
          version: ${{ matrix.nim }}
      - name: Build
        run: nimble install -y

      - name: Test
        run: nimble test -y

  status:
    if: always()
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')  || contains(needs.*.result, 'skipped') }}
        run: exit 1
